diplom/urls.py
from django.urls import path
from . import views
from django.conf.urls import url


urlpatterns = [
    path('', views.dis_list, name = 'dis_list'),
    path('discipline/<int:pk>/', views.dis_detail, name = 'dis_detail'),
    ]

mydiplom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diplom.urls')),
]

diplom/models.py
from django.db import models

# Create your models here.


class Discipline(models.Model):
    name = models.CharField(max_length=50)
    info = models.TextField()


    def __str__(self):
        return self.name


class Test(models.Model):
    discipline = models.ForeignKey(Discipline, default = 1,on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    info = models.TextField()


    def __str__(self):
        return self.name


class Question(models.Model):
    test = models.ForeignKey(Test, default = 1, on_delete=models.CASCADE)
    name = models.TextField()
    answer1 = models.TextField()
    answer2 = models.TextField()
    answer3 = models.TextField()
    answer4 = models.TextField()
    rigth_answer = models.IntegerField()

    count = models.IntegerField(default = 0)

    def __str__(self):
        return self.name

diplom/views.py
from django.shortcuts import render, get_object_or_404
from .models import Discipline, Test
from django.views import generic
from django.core.paginator import Paginator

# Create your views here.


def dis_list(request):
      dis = Discipline.objects.all()
      return render(request, 'diplom/dis_list.html', {'dis':dis})



def dis_detail(request, pk):
      dis = get_object_or_404(Discipline, pk = pk)
      return render(request, 'diplom/dis_detail.html', {'dis':dis})

diplom/templates/diplom/base.html
{% load static %}
<html>
    <head>
    <li align = 'right'><a href = '/admin'>Панель администратора</a></li>
        <title>Testing</title>
        <link rel="stylesheet" href="{% static 'css/diplom.css' %}">
    </head>
<body>
    <div class='page-header'>
        <h1><a href="/">Where, the fuck, i am?</a></h1>
    </div>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
         {% block content %}
         {% endblock %}  
        </div>
    </div>
</div>
</body>
</html>

diplom/templates/diplom/dis_detail.html
{%extends "diplom/base.html" %}

{%block content%}
                <div class='post'>
                 <h1>{{ dis.name }}</h1>
                    <input type='checkbox' id = 'info'>
                    <label for = 'info'>Информация: {{ dis.info}}</label>
            {% for t in dis.test_set.all %}
                <div class='post'>
                   <h1>{{t.name}}</h1>
                </div>
            {% endfor %}
                </div>

{%endblock%}

diplom/templates/diplom/dis_list.html
{%extends "diplom/base.html" %}

{%block content%}
            {% for post in dis %}
                <div class='post'>
                   <h1><a href="{% url 'dis_detail' pk=post.pk %}">{{ post.name }}</a></h1>
                     <p>Информация: {{ post.info}}</p>
                </div>
            {% endfor %}
{%endblock%}